#!/bin/bash

#CLOSURE_PATH=~/js/LambdaCert/jscert/interp/parser/lib/js_parser.jar

BASE_PATH=`dirname $0`/..

PARSER_PATH=.

OCAMLRUNPARAM="b" exec $BASE_PATH/build/eval.native -js -load $BASE_PATH/tests/es5.dump $@


