#!/bin/bash

S5_PATH=~/js/LambdaS5/src/s5.d.byte

BASE_PATH=`dirname $0`/..

$BASE_PATH/build/eval.native -desugarS5 $S5_PATH -load $BASE_PATH/tests/es5.dump $1

EX=$?

echo $0 $@ > /dev/tty

exit $EX
