#!/bin/bash

S5_PATH=~/js/LambdaS5/src/s5.d.byte

BASE_PATH=`dirname $0`/..

OCAMLRUNPARAM="b" $BASE_PATH/build/eval.native -desugarS5 -js $S5_PATH -load $BASE_PATH/tests/es5.dump $@

EX=$?

echo $0 $@ > /dev/tty

exit $EX
